global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: exporter-metrics

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s

    static_configs:
      # These endpoints are scraped via HTTP.
      - targets:
        - 'localhost:9090'
        - 'couchstats:9984'
