# Setting `log` here with the address of 127.0.0.1 will have the effect
# of haproxy sending the udp log messages to its own rsyslog instance
# (which sits at `127.0.0.1`) at the `local0` facility including all
# logs that have a priority greater or equal than debug
global
  maxconn  2046
  log      127.0.0.1       local0  debug

defaults
  log global

frontend http
         bind            :80
         default_backend backend_default

# A non-existent backend that would never return - again, this would
# be replaced by something that makes sense to your application, maybe
# something that gets generated whenever a new container goes up or
# it could be picked via DNS (as HAProxy now supports SRV records).
backend backend_default
        server local-server 127.0.0.1:5980
